refactor(portal): delegate the close responsability to the widget itself
infra-geo-ouverte/igo2 pull request #1142
Opened 2024-02-05 22:18 UTC by pelord

related to https://github.com/infra-geo-ouverte/igo2-lib/pull/1627

2025-02-03 21:17 UTC, alecarn approved these changes

2025-04-08 17:39 UTC, alecarn requested changes

2025-04-08 17:39 UTC, alecarn commented on src/app/pages/portal/portal.component.html
> -  </div>
Vu qu'on est au niveau d'une composante générique le WidgetComponent, il faudrait s'assurer que l'implémentation du onClose soit aussi générique?

2026-03-30 20:02 UTC, pelord commented
@alecarn Doit etre validé, car la composante de la lib a été mergé.

2026-03-31 13:47 UTC, alecarn approved these changes

2026-04-08 15:26 UTC, merged

2026-04-13 12:35 UTC, alecarn commented
:tada: This PR is included in version 20.1.0-next.8 :tada:

The release is available on [GitHub release](https://github.com/infra-geo-ouverte/igo2/releases/tag/v20.1.0-next.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2026-05-05 17:25 UTC, alecarn commented
:tada: This PR is included in version 20.1.0 :tada:

The release is available on [GitHub release](https://github.com/infra-geo-ouverte/igo2/releases/tag/v20.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: