feat(portal): new homeExtent button
infra-geo-ouverte/igo2 pull request #738
Opened 2022-02-10 17:48 UTC by mneige

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
The button to return to the home extent of the map is missing.

**What is the new behavior?**
The user can clic the button on the map to return to the home extent. The home extent can be defined (in config.json) for each portal and can be different from the initial extent. 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:
![image](https://user-images.githubusercontent.com/90412486/153457576-b4b7fd4a-5582-4a40-bdb4-fd90ec8dba3e.png)

2022-02-10 19:20 UTC, PhilippeLafreniere18 requested changes

2022-02-10 19:20 UTC, PhilippeLafreniere18 commented on src/config/interactiveTour.json
> +        "element": "#homeExtentButton",
Devrait rester tel quel à homeButton.
homeButton et homeExtentButton ne représente pas la même chose

2022-02-10 19:20 UTC, PhilippeLafreniere18 commented on src/contexts/_base.json
> +      "center": [73.938087, 49.000000],
pas nécessaire de pousser cette modif !

2022-02-10 19:20 UTC, PhilippeLafreniere18 commented on src/locale/fr.json
> +}
pas nécessaire de pousser cette modif !

2022-02-10 20:05 UTC, mneige commented on src/config/interactiveTour.json
> +        "element": "#homeExtentButton",
fixed

2022-02-10 20:05 UTC, mneige commented on src/contexts/_base.json
> +      "center": [73.938087, 49.000000],
c'est plus joli! le QC est plus à droite, ce qui laisse la place au menu, même en mode mobile

2022-02-10 20:09 UTC, mneige commented on src/locale/en.json
> -}
Elles ne viennent pas de moi, mais je les ai retirées!

2022-02-14 15:06 UTC, PhilippeLafreniere18 commented on src/contexts/_base.json
> +      "center": [73.938087, 49.000000],
Et correction, c'est -73.938087

2022-02-14 15:42 UTC, mneige commented on src/contexts/_base.json
> +      "center": [73.938087, 49.000000],
d'accord on retire ces changement!

2022-02-23 13:25 UTC, PhilippeLafreniere18 approved these changes

2022-02-23 13:26 UTC, PhilippeLafreniere18 commented
@mneige il faudrait seulement que tu refasses un merge origin/next (il y a des conflits avec next)

2022-03-28 16:05 UTC, pelord approved these changes

2022-03-28 16:06 UTC, merged