feat(portal) Wks new query behavior
infra-geo-ouverte/igo2 pull request #748
Opened 2022-03-03 21:28 UTC by josee666

** need to be integrate with PR in LIBS: 
https://github.com/infra-geo-ouverte/igo2-lib/pull/995

new query behavior: WFS and workspace/table attributaire

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ x] No
```

2022-03-16 20:43 UTC, pelord requested changes
voir mes commentaires ! Mais c'est vraiment bon.

2022-03-17 13:19 UTC, PhilippeLafreniere18 commented
@josee666 tu voudrais pousser tes couches de test dans le contexte workspace.json ?

2022-03-17 20:21 UTC, pelord commented
@josee666 @PhilippeLafreniere18  Il faudrait trouver une manière de faire le zoomto a partir de la table d'attribut
![image](https://user-images.githubusercontent.com/7397743/158888685-c92737ca-5bea-4e42-8b90-d05ea8ee009d.png)

2022-03-18 19:18 UTC, PhilippeLafreniere18 commented
> @josee666 @PhilippeLafreniere18 Il faudrait trouver une manière de faire le zoomto a partir de la table d'attribut ![image](https://user-images.githubusercontent.com/7397743/158888685-c92737ca-5bea-4e42-8b90-d05ea8ee009d.png)

L'ajouter dans le actions.service ? il va s'ajouter dans les actions des ...

2022-03-22 13:28 UTC, josee666 commented on src/app/pages/portal/portal.component.ts
> +    results = results.filter(x => x !== undefined);
fait!

2022-03-23 16:10 UTC, josee666 commented
pour le zoomTo déplacé dans https://github.com/infra-geo-ouverte/igo2/issues/751

2022-03-24 20:44 UTC, PhilippeLafreniere18 approved these changes

2022-03-24 20:46 UTC, merged