docs(geo): Forced Metadata documentation and examples
infra-geo-ouverte/igo2 pull request #798
Opened 2022-06-01 13:52 UTC by mneige

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:https://github.com/infra-geo-ouverte/igo2/blob/master/.github/CONTRIBUTING.md#git-commit-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Documentation doesn't cover the new Forced Metadata feature

**What is the new behavior?**
Documentation and examples are now provided in ReadTheDocs

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications:

**Other information**:

2022-06-06 20:21 UTC, pelord requested changes

2022-06-06 20:21 UTC, pelord commented on docs/_tables/fr/config/catalog.csv
>  |               - layerName: Nom de la couche dans le catalogue d'origine (propriété layer name). Permet d'aller chercher la couche en question dans le service.
je ne suis pas sur que c'est dans le bon format.....

2022-06-06 20:21 UTC, pelord commented on src/environments/environment.ts
> +                layerName: "All",
Je ne penses pas que ceci reflète ton code dans la lib 
![image](https://user-images.githubusercontent.com/7397743/172239614-9a8ed8e0-f3bb-4769-80dd-b92f1d0bcb2d.png)

2022-06-06 20:21 UTC, pelord commented on src/environments/environment.ts
> +                layerName: "All",
Que fait-on si  un layer se nomme All?
 allons y plutot avec *  ?

2022-06-06 20:21 UTC, pelord commented on src/environments/environment.ts
> +                  newMetadataUrl: 'https://www.donneesquebec.ca/',
newMetadataUrl ne semble pas fonctionner....

2022-06-14 18:30 UTC, mneige commented on src/app/pages/portal/portal.component.scss
> +igo-baselayers-switcher {
Je n'y ai pas touché

2022-06-22 17:41 UTC, PhilippeLafreniere18 approved these changes

2022-06-22 17:42 UTC, PhilippeLafreniere18 approved these changes

2022-06-22 17:42 UTC, merged