feat(geo): add new option to reverse coordinates lonLat to latLon
infra-geo-ouverte/igo2 pull request #890
Opened 2023-01-11 16:12 UTC by aziz-access

**What is the current behavior?** (You can also link to an open issue here)

this update relate to the issue #782;
this pull request refer to [1159](https://github.com/infra-geo-ouverte/igo2-lib/pull/1159) of igo2-lib

**What is the new behavior?**

Add new option in search settings to Reverse coords format from 'lonlat' to 'latLon'

2023-02-03 21:16 UTC, PhilippeLafreniere18 requested changes

2023-02-03 21:16 UTC, PhilippeLafreniere18 commented on src/app/pages/portal/portal.component.ts
> +      // this.authService.languageForce = true;
To remove

2023-02-03 21:17 UTC, aziz-access commented on src/app/pages/portal/portal.component.ts
> +      // this.authService.languageForce = true;
ok

2023-02-23 18:47 UTC, PhilippeLafreniere18 approved these changes

2023-03-15 13:30 UTC, merged